 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

#include "../include/RooSpinZero.h" 

RooSpinZero::RooSpinZero(
  const char* name, const char* title,
  modelMeasurables _measurables,
  modelParameters _parameters
  ) : RooAbsPdf(name, title),
  h1("h1", "h1", this, (RooAbsReal&)*(_measurables.h1)),
  h2("h2", "h2", this, (RooAbsReal&)*(_measurables.h2)),
  Phi("Phi", "Phi", this, (RooAbsReal&)*(_measurables.Phi)),
  m1("m1", "m1", this, (RooAbsReal&)*(_measurables.m1)),
  m2("m2", "m2", this, (RooAbsReal&)*(_measurables.m2)),
  m12("m12", "m12", this, (RooAbsReal&)*(_measurables.m12)),
  hs("hs", "hs", this, (RooAbsReal&)*(_measurables.hs)),
  Phi1("Phi1", "Phi1", this, (RooAbsReal&)*(_measurables.Phi1)),
  Y("Y", "Y", this, (RooAbsReal&)*(_measurables.Y)),

  mX("mX", "mX", this, (RooAbsReal&)*(_parameters.mX)),
  gamX("gamX", "gamX", this, (RooAbsReal&)*(_parameters.gamX)),
  mV("mV", "mV", this, (RooAbsReal&)*(_parameters.mV)),
  gamV("gamV", "gamV", this, (RooAbsReal&)*(_parameters.gamV)),
  R1Val("R1Val", "R1Val", this, (RooAbsReal&)*(_parameters.R1Val)),
  R2Val("R2Val", "R2Val", this, (RooAbsReal&)*(_parameters.R2Val)),

  g1Val("g1Val", "g1Val", this, (RooAbsReal&)*(_parameters.g1List[0][0])),
  g2Val("g2Val", "g2Val", this, (RooAbsReal&)*(_parameters.g2List[0][0])),
  g3Val("g3Val", "g3Val", this, (RooAbsReal&)*(_parameters.g3List[0][0])),
  g4Val("g4Val", "g4Val", this, (RooAbsReal&)*(_parameters.g4List[0][0])),

  g1_primeVal("g1_primeVal", "g1_primeVal", this, (RooAbsReal&)*(_parameters.g1List[1][0])),
  g2_primeVal("g2_primeVal", "g2_primeVal", this, (RooAbsReal&)*(_parameters.g2List[1][0])),
  g3_primeVal("g3_primeVal", "g3_primeVal", this, (RooAbsReal&)*(_parameters.g3List[1][0])),
  g4_primeVal("g4_primeVal", "g4_primeVal", this, (RooAbsReal&)*(_parameters.g4List[1][0])),

  g1_prime2Val("g1_prime2Val", "g1_prime2Val", this, (RooAbsReal&)*(_parameters.g1List[2][0])),
  g2_prime2Val("g2_prime2Val", "g2_prime2Val", this, (RooAbsReal&)*(_parameters.g2List[2][0])),
  g3_prime2Val("g3_prime2Val", "g3_prime2Val", this, (RooAbsReal&)*(_parameters.g3List[2][0])),
  g4_prime2Val("g4_prime2Val", "g4_prime2Val", this, (RooAbsReal&)*(_parameters.g4List[2][0])),

  g1_prime3Val("g1_prime3Val", "g1_prime3Val", this, (RooAbsReal&)*(_parameters.g1List[3][0])),
  g2_prime3Val("g2_prime3Val", "g2_prime3Val", this, (RooAbsReal&)*(_parameters.g2List[3][0])),
  g3_prime3Val("g3_prime3Val", "g3_prime3Val", this, (RooAbsReal&)*(_parameters.g3List[3][0])),
  g4_prime3Val("g4_prime3Val", "g4_prime3Val", this, (RooAbsReal&)*(_parameters.g4List[3][0])),

  g1_prime4Val("g1_prime4Val", "g1_prime4Val", this, (RooAbsReal&)*(_parameters.g1List[4][0])),
  g2_prime4Val("g2_prime4Val", "g2_prime4Val", this, (RooAbsReal&)*(_parameters.g2List[4][0])),
  g3_prime4Val("g3_prime4Val", "g3_prime4Val", this, (RooAbsReal&)*(_parameters.g3List[4][0])),
  g4_prime4Val("g4_prime4Val", "g4_prime4Val", this, (RooAbsReal&)*(_parameters.g4List[4][0])),

  g1_prime5Val("g1_prime5Val", "g1_prime5Val", this, (RooAbsReal&)*(_parameters.g1List[5][0])),
  g2_prime5Val("g2_prime5Val", "g2_prime5Val", this, (RooAbsReal&)*(_parameters.g2List[5][0])),
  g3_prime5Val("g3_prime5Val", "g3_prime5Val", this, (RooAbsReal&)*(_parameters.g3List[5][0])),
  g4_prime5Val("g4_prime5Val", "g4_prime5Val", this, (RooAbsReal&)*(_parameters.g4List[5][0])),

  g1_prime6Val("g1_prime6Val", "g1_prime6Val", this, (RooAbsReal&)*(_parameters.g1List[6][0])),
  g2_prime6Val("g2_prime6Val", "g2_prime6Val", this, (RooAbsReal&)*(_parameters.g2List[6][0])),
  g3_prime6Val("g3_prime6Val", "g3_prime6Val", this, (RooAbsReal&)*(_parameters.g3List[6][0])),
  g4_prime6Val("g4_prime6Val", "g4_prime6Val", this, (RooAbsReal&)*(_parameters.g4List[6][0])),

  g1_prime7Val("g1_prime7Val", "g1_prime7Val", this, (RooAbsReal&)*(_parameters.g1List[7][0])),
  g2_prime7Val("g2_prime7Val", "g2_prime7Val", this, (RooAbsReal&)*(_parameters.g2List[7][0])),
  g3_prime7Val("g3_prime7Val", "g3_prime7Val", this, (RooAbsReal&)*(_parameters.g3List[7][0])),
  g4_prime7Val("g4_prime7Val", "g4_prime7Val", this, (RooAbsReal&)*(_parameters.g4List[7][0])),

  g1ValIm("g1ValIm", "g1ValIm", this, (RooAbsReal&)*(_parameters.g1List[0][1])),
  g2ValIm("g2ValIm", "g2ValIm", this, (RooAbsReal&)*(_parameters.g2List[0][1])),
  g3ValIm("g3ValIm", "g3ValIm", this, (RooAbsReal&)*(_parameters.g3List[0][1])),
  g4ValIm("g4ValIm", "g4ValIm", this, (RooAbsReal&)*(_parameters.g4List[0][1])),

  g1_primeValIm("g1_primeValIm", "g1_primeValIm", this, (RooAbsReal&)*(_parameters.g1List[1][1])),
  g2_primeValIm("g2_primeValIm", "g2_primeValIm", this, (RooAbsReal&)*(_parameters.g2List[1][1])),
  g3_primeValIm("g3_primeValIm", "g3_primeValIm", this, (RooAbsReal&)*(_parameters.g3List[1][1])),
  g4_primeValIm("g4_primeValIm", "g4_primeValIm", this, (RooAbsReal&)*(_parameters.g4List[1][1])),

  g1_prime2ValIm("g1_prime2ValIm", "g1_prime2ValIm", this, (RooAbsReal&)*(_parameters.g1List[2][1])),
  g2_prime2ValIm("g2_prime2ValIm", "g2_prime2ValIm", this, (RooAbsReal&)*(_parameters.g2List[2][1])),
  g3_prime2ValIm("g3_prime2ValIm", "g3_prime2ValIm", this, (RooAbsReal&)*(_parameters.g3List[2][1])),
  g4_prime2ValIm("g4_prime2ValIm", "g4_prime2ValIm", this, (RooAbsReal&)*(_parameters.g4List[2][1])),

  g1_prime3ValIm("g1_prime3ValIm", "g1_prime3ValIm", this, (RooAbsReal&)*(_parameters.g1List[3][1])),
  g2_prime3ValIm("g2_prime3ValIm", "g2_prime3ValIm", this, (RooAbsReal&)*(_parameters.g2List[3][1])),
  g3_prime3ValIm("g3_prime3ValIm", "g3_prime3ValIm", this, (RooAbsReal&)*(_parameters.g3List[3][1])),
  g4_prime3ValIm("g4_prime3ValIm", "g4_prime3ValIm", this, (RooAbsReal&)*(_parameters.g4List[3][1])),

  g1_prime4ValIm("g1_prime4ValIm", "g1_prime4ValIm", this, (RooAbsReal&)*(_parameters.g1List[4][1])),
  g2_prime4ValIm("g2_prime4ValIm", "g2_prime4ValIm", this, (RooAbsReal&)*(_parameters.g2List[4][1])),
  g3_prime4ValIm("g3_prime4ValIm", "g3_prime4ValIm", this, (RooAbsReal&)*(_parameters.g3List[4][1])),
  g4_prime4ValIm("g4_prime4ValIm", "g4_prime4ValIm", this, (RooAbsReal&)*(_parameters.g4List[4][1])),

  g1_prime5ValIm("g1_prime5ValIm", "g1_prime5ValIm", this, (RooAbsReal&)*(_parameters.g1List[5][1])),
  g2_prime5ValIm("g2_prime5ValIm", "g2_prime5ValIm", this, (RooAbsReal&)*(_parameters.g2List[5][1])),
  g3_prime5ValIm("g3_prime5ValIm", "g3_prime5ValIm", this, (RooAbsReal&)*(_parameters.g3List[5][1])),
  g4_prime5ValIm("g4_prime5ValIm", "g4_prime5ValIm", this, (RooAbsReal&)*(_parameters.g4List[5][1])),

  g1_prime6ValIm("g1_prime6ValIm", "g1_prime6ValIm", this, (RooAbsReal&)*(_parameters.g1List[6][1])),
  g2_prime6ValIm("g2_prime6ValIm", "g2_prime6ValIm", this, (RooAbsReal&)*(_parameters.g2List[6][1])),
  g3_prime6ValIm("g3_prime6ValIm", "g3_prime6ValIm", this, (RooAbsReal&)*(_parameters.g3List[6][1])),
  g4_prime6ValIm("g4_prime6ValIm", "g4_prime6ValIm", this, (RooAbsReal&)*(_parameters.g4List[6][1])),

  g1_prime7ValIm("g1_prime7ValIm", "g1_prime7ValIm", this, (RooAbsReal&)*(_parameters.g1List[7][1])),
  g2_prime7ValIm("g2_prime7ValIm", "g2_prime7ValIm", this, (RooAbsReal&)*(_parameters.g2List[7][1])),
  g3_prime7ValIm("g3_prime7ValIm", "g3_prime7ValIm", this, (RooAbsReal&)*(_parameters.g3List[7][1])),
  g4_prime7ValIm("g4_prime7ValIm", "g4_prime7ValIm", this, (RooAbsReal&)*(_parameters.g4List[7][1])),

  Lambda("Lambda", "Lambda", this, (RooAbsReal&)*(_parameters.Lambda)),
  Lambda_z1("Lambda_z1", "Lambda_z1", this, (RooAbsReal&)*(_parameters.Lambda_z1)),
  Lambda_z2("Lambda_z2", "Lambda_z2", this, (RooAbsReal&)*(_parameters.Lambda_z2)),
  Lambda_z3("Lambda_z3", "Lambda_z3", this, (RooAbsReal&)*(_parameters.Lambda_z3)),
  Lambda_z4("Lambda_z4", "Lambda_z4", this, (RooAbsReal&)*(_parameters.Lambda_z4)),
  Lambda_Q("Lambda_Q", "Lambda_Q", this, (RooAbsReal&)*(_parameters.Lambda_Q))
{}


RooSpinZero::RooSpinZero(const RooSpinZero& other, const char* name) :
RooAbsPdf(other, name),
h1("h1", this, other.h1),
h2("h2", this, other.h2),
Phi("Phi", this, other.Phi),
m1("m1", this, other.m1),
m2("m2", this, other.m2),
m12("m12", this, other.m12),
hs("hs", this, other.hs),
Phi1("Phi1", this, other.Phi1),
Y("Y", this, other.Y),

mX("mX", this, other.mX),
gamX("gamX", this, other.gamX),
mV("mV", this, other.mV),
gamV("gamV", this, other.gamV),
R1Val("R1Val", this, other.R1Val),
R2Val("R2Val", this, other.R2Val),

g1Val("g1Val", this, other.g1Val),
g2Val("a2Val", this, other.g2Val),
g3Val("g3Val", this, other.g3Val),
g4Val("g4Val", this, other.g4Val),

g1_primeVal("g1_primeVal", this, other.g1_primeVal),
g2_primeVal("a2_primeVal", this, other.g2_primeVal),
g3_primeVal("g3_primeVal", this, other.g3_primeVal),
g4_primeVal("g4_primeVal", this, other.g4_primeVal),

g1_prime2Val("g1_prime2Val", this, other.g1_prime2Val),
g2_prime2Val("a2_prime2Val", this, other.g2_prime2Val),
g3_prime2Val("g3_prime2Val", this, other.g3_prime2Val),
g4_prime2Val("g4_prime2Val", this, other.g4_prime2Val),

g1_prime3Val("g1_prime3Val", this, other.g1_prime3Val),
g2_prime3Val("a2_prime3Val", this, other.g2_prime3Val),
g3_prime3Val("g3_prime3Val", this, other.g3_prime3Val),
g4_prime3Val("g4_prime3Val", this, other.g4_prime3Val),

g1_prime4Val("g1_prime4Val", this, other.g1_prime4Val),
g2_prime4Val("a2_prime4Val", this, other.g2_prime4Val),
g3_prime4Val("g3_prime4Val", this, other.g3_prime4Val),
g4_prime4Val("g4_prime4Val", this, other.g4_prime4Val),

g1_prime5Val("g1_prime5Val", this, other.g1_prime5Val),
g2_prime5Val("a2_prime5Val", this, other.g2_prime5Val),
g3_prime5Val("g3_prime5Val", this, other.g3_prime5Val),
g4_prime5Val("g4_prime5Val", this, other.g4_prime5Val),

g1_prime6Val("g1_prime6Val", this, other.g1_prime6Val),
g2_prime6Val("a2_prime6Val", this, other.g2_prime6Val),
g3_prime6Val("g3_prime6Val", this, other.g3_prime6Val),
g4_prime6Val("g4_prime6Val", this, other.g4_prime6Val),

g1_prime7Val("g1_prime7Val", this, other.g1_prime7Val),
g2_prime7Val("a2_prime7Val", this, other.g2_prime7Val),
g3_prime7Val("g3_prime7Val", this, other.g3_prime7Val),
g4_prime7Val("g4_prime7Val", this, other.g4_prime7Val),

g1ValIm("g1ValIm", this, other.g1ValIm),
g2ValIm("a2ValIm", this, other.g2ValIm),
g3ValIm("g3ValIm", this, other.g3ValIm),
g4ValIm("g4ValIm", this, other.g4ValIm),

g1_primeValIm("g1_primeValIm", this, other.g1_primeValIm),
g2_primeValIm("a2_primeValIm", this, other.g2_primeValIm),
g3_primeValIm("g3_primeValIm", this, other.g3_primeValIm),
g4_primeValIm("g4_primeValIm", this, other.g4_primeValIm),

g1_prime2ValIm("g1_prime2ValIm", this, other.g1_prime2ValIm),
g2_prime2ValIm("a2_prime2ValIm", this, other.g2_prime2ValIm),
g3_prime2ValIm("g3_prime2ValIm", this, other.g3_prime2ValIm),
g4_prime2ValIm("g4_prime2ValIm", this, other.g4_prime2ValIm),

g1_prime3ValIm("g1_prime3ValIm", this, other.g1_prime3ValIm),
g2_prime3ValIm("a2_prime3ValIm", this, other.g2_prime3ValIm),
g3_prime3ValIm("g3_prime3ValIm", this, other.g3_prime3ValIm),
g4_prime3ValIm("g4_prime3ValIm", this, other.g4_prime3ValIm),

g1_prime4ValIm("g1_prime4ValIm", this, other.g1_prime4ValIm),
g2_prime4ValIm("a2_prime4ValIm", this, other.g2_prime4ValIm),
g3_prime4ValIm("g3_prime4ValIm", this, other.g3_prime4ValIm),
g4_prime4ValIm("g4_prime4ValIm", this, other.g4_prime4ValIm),

g1_prime5ValIm("g1_prime5ValIm", this, other.g1_prime5ValIm),
g2_prime5ValIm("a2_prime5ValIm", this, other.g2_prime5ValIm),
g3_prime5ValIm("g3_prime5ValIm", this, other.g3_prime5ValIm),
g4_prime5ValIm("g4_prime5ValIm", this, other.g4_prime5ValIm),

g1_prime6ValIm("g1_prime6ValIm", this, other.g1_prime6ValIm),
g2_prime6ValIm("a2_prime6ValIm", this, other.g2_prime6ValIm),
g3_prime6ValIm("g3_prime6ValIm", this, other.g3_prime6ValIm),
g4_prime6ValIm("g4_prime6ValIm", this, other.g4_prime6ValIm),

g1_prime7ValIm("g1_prime7ValIm", this, other.g1_prime7ValIm),
g2_prime7ValIm("a2_prime7ValIm", this, other.g2_prime7ValIm),
g3_prime7ValIm("g3_prime7ValIm", this, other.g3_prime7ValIm),
g4_prime7ValIm("g4_prime7ValIm", this, other.g4_prime7ValIm),

Lambda("Lambda", this, other.Lambda),
Lambda_z1("Lambda_z1", this, other.Lambda_z1),
Lambda_z2("Lambda_z2", this, other.Lambda_z2),
Lambda_z3("Lambda_z3", this, other.Lambda_z3),
Lambda_z4("Lambda_z4", this, other.Lambda_z4),
Lambda_Q("Lambda_Q", this, other.Lambda_Q)
{}

void RooSpinZero::calculateAiPhiAi(Double_t& a1Re, Double_t& a1Im, Double_t& a2Re, Double_t& a2Im, Double_t& a3Re, Double_t& a3Im)const{
  Double_t g1_dyn = g1Val
    +   g1_primeVal * pow(Lambda_z1, 4)/(pow(Lambda_z1, 2) + pow(m1, 2))/(pow(Lambda_z1, 2) + pow(m2, 2))
    +   g1_prime2Val* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z1, 2)
    +   g1_prime3Val* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z1, 2)
    +   g1_prime4Val* (m12*m12)/pow(Lambda_Q, 2)
    +   g1_prime5Val* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z1, 4)
    +   g1_prime6Val* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z1, 4)
    +   g1_prime7Val* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z1, 4);

  Double_t g2_dyn = g2Val
    +   g2_primeVal * pow(Lambda_z2, 4)/(pow(Lambda_z2, 2) + pow(m1, 2))/(pow(Lambda_z2, 2) + pow(m2, 2))
    +   g2_prime2Val* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z2, 2)
    +   g2_prime3Val* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z2, 2)
    +   g2_prime4Val* (m12*m12)/pow(Lambda_Q, 2)
    +   g2_prime5Val* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z2, 4)
    +   g2_prime6Val* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z2, 4)
    +   g2_prime7Val* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z2, 4);

  Double_t g3_dyn = g3Val
    +   g3_primeVal * pow(Lambda_z3, 4)/(pow(Lambda_z3, 2) + pow(m1, 2))/(pow(Lambda_z3, 2) + pow(m2, 2))
    +   g3_prime2Val* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z3, 2)
    +   g3_prime3Val* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z3, 2)
    +   g3_prime4Val* (m12*m12)/pow(Lambda_Q, 2)
    +   g3_prime5Val* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z3, 4)
    +   g3_prime6Val* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z3, 4)
    +   g3_prime7Val* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z3, 4);

  Double_t g4_dyn = g4Val
    +   g4_primeVal * pow(Lambda_z4, 4)/(pow(Lambda_z4, 2) + pow(m1, 2))/(pow(Lambda_z4, 2) + pow(m2, 2))
    +   g4_prime2Val* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z4, 2)
    +   g4_prime3Val* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z4, 2)
    +   g4_prime4Val* (m12*m12)/pow(Lambda_Q, 2)
    +   g4_prime5Val* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z4, 4)
    +   g4_prime6Val* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z4, 4)
    +   g4_prime7Val* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z4, 4);

  Double_t g1_dynIm = g1ValIm
    +   g1_primeValIm * pow(Lambda_z1, 4)/(pow(Lambda_z1, 2) + pow(m1, 2))/(pow(Lambda_z1, 2) + pow(m2, 2))
    +   g1_prime2ValIm* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z1, 2)
    +   g1_prime3ValIm* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z1, 2)
    +   g1_prime4ValIm* (m12*m12)/pow(Lambda_Q, 2)
    +   g1_prime5ValIm* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z1, 4)
    +   g1_prime6ValIm* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z1, 4)
    +   g1_prime7ValIm* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z1, 4);

  Double_t g2_dynIm = g2ValIm
    +   g2_primeValIm * pow(Lambda_z2, 4)/(pow(Lambda_z2, 2) + pow(m1, 2))/(pow(Lambda_z2, 2) + pow(m2, 2))
    +   g2_prime2ValIm* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z2, 2)
    +   g2_prime3ValIm* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z2, 2)
    +   g2_prime4ValIm* (m12*m12)/pow(Lambda_Q, 2)
    +   g2_prime5ValIm* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z2, 4)
    +   g2_prime6ValIm* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z2, 4)
    +   g2_prime7ValIm* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z2, 4);

  Double_t g3_dynIm = g3ValIm
    +   g3_primeValIm * pow(Lambda_z3, 4)/(pow(Lambda_z3, 2) + pow(m1, 2))/(pow(Lambda_z3, 2) + pow(m2, 2))
    +   g3_prime2ValIm* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z3, 2)
    +   g3_prime3ValIm* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z3, 2)
    +   g3_prime4ValIm* (m12*m12)/pow(Lambda_Q, 2)
    +   g3_prime5ValIm* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z3, 4)
    +   g3_prime6ValIm* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z3, 4)
    +   g3_prime7ValIm* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z3, 4);

  Double_t g4_dynIm = g4ValIm
    +   g4_primeValIm * pow(Lambda_z4, 4)/(pow(Lambda_z4, 2) + pow(m1, 2))/(pow(Lambda_z4, 2) + pow(m2, 2))
    +   g4_prime2ValIm* (pow(m1, 2) + pow(m2, 2))/pow(Lambda_z4, 2)
    +   g4_prime3ValIm* (pow(m1, 2) - pow(m2, 2))/pow(Lambda_z4, 2)
    +   g4_prime4ValIm* (m12*m12)/pow(Lambda_Q, 2)
    +   g4_prime5ValIm* (pow(m1, 4) + pow(m2, 4))/pow(Lambda_z4, 4)
    +   g4_prime6ValIm* (pow(m1, 4) - pow(m2, 4))/pow(Lambda_z4, 4)
    +   g4_prime7ValIm* (pow(m1, 2) * pow(m2, 2))/pow(Lambda_z4, 4);

  Double_t s = (pow(m12, 2) - pow(m1, 2) - pow(m2, 2))/2.;
  if (pow(m1, 2)>pow(m12, 2) || pow(m2, 2)>pow(m12, 2)) s = -s;
  Double_t kappa = s/pow(Lambda,2);

  a1Re = g1_dyn*pow(mV/m12, 2) + g2_dyn*2.*s/pow(m12, 2) + g3_dyn*kappa*s/pow(m12, 2);
  a2Re = -2.*g2_dyn - g3_dyn*kappa;
  a3Re = -2.*g4_dyn;
  a1Im = g1_dynIm*pow(mV/m12, 2) + g2_dynIm*2.*s/pow(m12, 2) + g3_dynIm*kappa*s/pow(m12, 2);
  a2Im = -2.*g2_dynIm - g3_dynIm*kappa;
  a3Im = -2.*g4_dynIm;
}
void RooSpinZero::calculateAmplitudes(Double_t& A00Re, Double_t& A00Im, Double_t& AppRe, Double_t& AppIm, Double_t& AmmRe, Double_t& AmmIm)const{
  Double_t a1Re, a2Re, a3Re, a1Im, a2Im, a3Im;
  calculateAiPhiAi(a1Re, a1Im, a2Re, a2Im, a3Re, a3Im);

  Double_t x = (pow(m12, 2) - pow(m1, 2) - pow(m2, 2))/(2.0*m1*m2);
  if (pow(m1, 2)>pow(m12, 2) || pow(m2, 2)>pow(m12, 2)) x = -x;
  Double_t xsqmo = pow(x, 2) - 1.;

  A00Re =
    -(
    a1Re*x*pow(m12,2)
    +a2Re*xsqmo*m1*m2
    );
  A00Im =
    -(
    a1Im*x*pow(m12, 2)
    +a2Im*xsqmo*m1*m2
    );

  AppRe = a1Re*pow(m12, 2) - a3Im*sqrt(xsqmo)*m1*m2;
  AppIm = a1Im*pow(m12, 2) + a3Re*sqrt(xsqmo)*m1*m2;

  AmmRe = a1Re*pow(m12, 2) + a3Im*sqrt(xsqmo)*m1*m2;
  AmmIm = a1Im*pow(m12, 2) - a3Re*sqrt(xsqmo)*m1*m2;
}


