/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSPINZERO
#define ROOSPINZERO

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooRealVar.h"
#include "RooAbsCategory.h"
#include "Riostream.h" 
#include <cmath>
#include "TMath.h"

using namespace TMath;

enum parameterizationList { kMagPhase_As=0, kRealImag_Gs=1, kFracPhase_Gs=2, kNUMparameterizations=3 };

#endif
