/*****************************************************************************
* Project: RooFit                                                           *
*                                                                           *
* This code was autogenerated by RooClassFactory                            *
*****************************************************************************/

#ifndef ROOSPINZERO
#define ROOSPINZERO

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooRealVar.h"
#include "RooFormulaVar.h"
#include "RooAbsCategory.h"
#include "Riostream.h" 
#include <cmath>
#include "TMath.h"

using namespace TMath;

class RooSpinZero : public RooAbsPdf {
public:

  struct modelMeasurables{
    RooRealVar* h1;
    RooRealVar* h2;
    RooRealVar* Phi;
    RooRealVar* m1;
    RooRealVar* m2;
    RooRealVar* m12;
    RooRealVar* hs;
    RooRealVar* Phi1;
    RooRealVar* Y;
  };
  struct modelParameters{
    RooRealVar* mX;
    RooRealVar* gamX;
    RooRealVar* mV;
    RooRealVar* gamV;
    RooRealVar* R1Val;
    RooRealVar* R2Val;

    RooAbsReal* g1List[8][2];
    RooAbsReal* g2List[8][2];
    RooAbsReal* g3List[8][2];
    RooAbsReal* g4List[8][2];

    RooRealVar* Lambda;
    RooRealVar* Lambda_z1;
    RooRealVar* Lambda_z2;
    RooRealVar* Lambda_z3;
    RooRealVar* Lambda_z4;
    RooRealVar* Lambda_Q;

    RooRealVar* Lambda_z1qsq[3];
    RooRealVar* Lambda_z2qsq[3];
    RooRealVar* Lambda_z3qsq[3];
    RooRealVar* Lambda_z4qsq[3];
    RooRealVar* cLambda_qsq[3];
  };

  RooSpinZero(){};
  RooSpinZero(
    const char* name, const char* title,
    modelMeasurables _measurables,
    modelParameters _parameters
    );

  RooSpinZero(const RooSpinZero& other, const char* name=0);
  virtual TObject* clone(const char* newname) const = 0;
  inline virtual ~RooSpinZero() {}

  virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const = 0;
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const = 0;

  virtual void setProxy(RooRealProxy& proxy, RooAbsReal* objectPtr);

protected:

  RooRealProxy h1;
  RooRealProxy h2;
  RooRealProxy Phi;
  RooRealProxy m1;
  RooRealProxy m2;
  RooRealProxy m12;
  RooRealProxy hs;
  RooRealProxy Phi1;
  RooRealProxy Y;

  RooRealProxy mX;
  RooRealProxy gamX;
  RooRealProxy mV;
  RooRealProxy gamV;
  RooRealProxy R1Val;
  RooRealProxy R2Val;

  RooRealProxy g1Val;
  RooRealProxy g2Val;
  RooRealProxy g3Val;
  RooRealProxy g4Val;
  RooRealProxy g1_primeVal;
  RooRealProxy g2_primeVal;
  RooRealProxy g3_primeVal;
  RooRealProxy g4_primeVal;
  RooRealProxy g1_prime2Val;
  RooRealProxy g2_prime2Val;
  RooRealProxy g3_prime2Val;
  RooRealProxy g4_prime2Val;
  RooRealProxy g1_prime3Val;
  RooRealProxy g2_prime3Val;
  RooRealProxy g3_prime3Val;
  RooRealProxy g4_prime3Val;
  RooRealProxy g1_prime4Val;
  RooRealProxy g2_prime4Val;
  RooRealProxy g3_prime4Val;
  RooRealProxy g4_prime4Val;
  RooRealProxy g1_prime5Val;
  RooRealProxy g2_prime5Val;
  RooRealProxy g3_prime5Val;
  RooRealProxy g4_prime5Val;
  RooRealProxy g1_prime6Val;
  RooRealProxy g2_prime6Val;
  RooRealProxy g3_prime6Val;
  RooRealProxy g4_prime6Val;
  RooRealProxy g1_prime7Val;
  RooRealProxy g2_prime7Val;
  RooRealProxy g3_prime7Val;
  RooRealProxy g4_prime7Val;

  RooRealProxy g1ValIm;
  RooRealProxy g2ValIm;
  RooRealProxy g3ValIm;
  RooRealProxy g4ValIm;
  RooRealProxy g1_primeValIm;
  RooRealProxy g2_primeValIm;
  RooRealProxy g3_primeValIm;
  RooRealProxy g4_primeValIm;
  RooRealProxy g1_prime2ValIm;
  RooRealProxy g2_prime2ValIm;
  RooRealProxy g3_prime2ValIm;
  RooRealProxy g4_prime2ValIm;
  RooRealProxy g1_prime3ValIm;
  RooRealProxy g2_prime3ValIm;
  RooRealProxy g3_prime3ValIm;
  RooRealProxy g4_prime3ValIm;
  RooRealProxy g1_prime4ValIm;
  RooRealProxy g2_prime4ValIm;
  RooRealProxy g3_prime4ValIm;
  RooRealProxy g4_prime4ValIm;
  RooRealProxy g1_prime5ValIm;
  RooRealProxy g2_prime5ValIm;
  RooRealProxy g3_prime5ValIm;
  RooRealProxy g4_prime5ValIm;
  RooRealProxy g1_prime6ValIm;
  RooRealProxy g2_prime6ValIm;
  RooRealProxy g3_prime6ValIm;
  RooRealProxy g4_prime6ValIm;
  RooRealProxy g1_prime7ValIm;
  RooRealProxy g2_prime7ValIm;
  RooRealProxy g3_prime7ValIm;
  RooRealProxy g4_prime7ValIm;

  RooRealProxy Lambda;
  RooRealProxy Lambda_z1;
  RooRealProxy Lambda_z2;
  RooRealProxy Lambda_z3;
  RooRealProxy Lambda_z4;
  RooRealProxy Lambda_Q;

  RooRealProxy Lambda_z11;
  RooRealProxy Lambda_z21;
  RooRealProxy Lambda_z31;
  RooRealProxy Lambda_z41;
  RooRealProxy Lambda_z12;
  RooRealProxy Lambda_z22;
  RooRealProxy Lambda_z32;
  RooRealProxy Lambda_z42;
  RooRealProxy Lambda_z10;
  RooRealProxy Lambda_z20;
  RooRealProxy Lambda_z30;
  RooRealProxy Lambda_z40;
  RooRealProxy cz_q1sq;
  RooRealProxy cz_q2sq;
  RooRealProxy cz_q12sq;

  virtual Double_t evaluate() const = 0;

  virtual void calculateAiPhiAi(Double_t& a1Re, Double_t& a1Im, Double_t& a2Re, Double_t& a2Im, Double_t& a3Re, Double_t& a3Im) const;
  virtual void calculateAmplitudes(Double_t& A00Re, Double_t& A00Im, Double_t& AppRe, Double_t& AppIm, Double_t& AmmRe, Double_t& AmmIm) const;

  virtual void setProxies(modelMeasurables _measurables);
};

#endif
